language: python
sudo: false

arch:
  - amd64
  - arm64

python:
  - "3.6"

install:
  - pip -q install testresources==0.2.7
  - pip -q install -r dev_requirements.txt
  - pip -q install gevent || echo "Couldn't install gevent"
  - pip -q install twisted || echo "Couldn't install Twisted"
  - git describe --tags --long --always
  - python setup.py build_ext --inplace
  - python setup.py install

script:
  - python -m couchbase.bucket
  - cp .tests.ini.travis tests.ini
  - nosetests -v couchbase_tests.test_sync
  - nosetests -v acouchbase
  - nosetests -v txcouchbase || echo "Twisted tests failed"

notifications:
  email:
    - PythonPackage@couchbase.com
